services:
    calendar_db:
        image: mysql:latest
        restart: always
        container_name: calendarDB
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3201:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env
        command: --max_connections=100000000

    calendar:
        image: node:hydrogen-slim
        container_name: calendar
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3200:3200
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
